stages:
  - development
  - release

variables:
  GIT_CLEAN_FLAGS: -n

after_script:
  - docker image prune -f
  - echo "done"

development:
  stage: development
  script:
    #- git-docker -c dev-vasHomePage -i gitlab.vascomm.co.id:4567/vaswebsite/vashomepage:latest_dev
    - docker-compose -f docker-compose.dev.yml build
    - docker-compose -f docker-compose.dev.yml up -d --force-recreate --build dev-commjwebplatform
  tags:
    - development
  only:
    - development

release:
  stage: release
  script:
    # to set environtment production / testing
    # - sed -i 's/development/production/' app.json
    - docker-compose -f docker-compose.release.yml build
    - docker-compose -f docker-compose.release.yml up -d --force-recreate
  tags:
    - release
  only:
    - release
