stages:
  - development
  - production

variables:
  GIT_CLEAN_FLAGS: -n
    
before_script:
  #- export http_proxy=http://192.168.13.6:3128
  #- export https_proxy=http://192.168.13.6:3128

after_script:
  - docker image prune -f
  - echo "done"

development:
  stage: development
  script:
    #- git-docker -c dev-vasHomePage -i gitlab.vascomm.co.id:4567/vaswebsite/vashomepage:latest_dev
    - docker-compose -f docker-compose.dev.yml build
    - docker-compose -f docker-compose.dev.yml up -d --force-recreate
  tags:
    - development
  only:
    - development

production:
  stage: production
  script:
    # to set environtment production / testing
    # - sed -i 's/development/production/' app.json
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate
  tags:
    - production
  only:
    - master
