version: '3.7'

services:
  prod-commjaweb:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: gitlab.vascomm.co.id:4567/commjunction/web-platform:latest_prod
    volumes:
      # - ./:/var/www/html
      - /home/apps/config_env/web_commj/.env:/var/www/html/.env
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      # - /var/www/html/vendor
      - /home/apps/log:/var/log/nginx/access
    networks:
      - vascomm-app
    container_name: prod-commjaweb
    ports:
      - 9899:80
    tty: true
    restart: always
  
networks:
  vascomm-app:
    name: vascomm-app
    driver: bridge

