version: '3.7'
services:
  dev-platform-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gitlab.vascomm.co.id:4567/commjunction/web-platform:latest_dev
    volumes:
      - /home/apps/config_env/web_commj/.env:/var/www/html/.env
      - ./:/var/www/html
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/html/vendor
      - /home/apps/log:/var/log/nginx/access
    container_name: dev-commjaweb
    ports:
      - 9899:80
    tty: true
    restart: always
    
    networks:
      - vascomm-app
          
  
networks:
  vascomm-app:
     name : vascomm-app
     driver : bridge


